### ISSUE TITLE
Need Tutorial Videos Link

### ISSUE THREAD

**Issue by VarunSaiTeja** [BillWagner/MVA-LINQ#2]
After Microsoft Virtual Academy site retired i am not able to see your videos series of
Demystifying LINQ.

So that is there any site where you posted those videos other than MVA?

**Comment by VarunSaiTeja** [comment]
Can you provide video tutorials link, MVA site has been terminated by microsoft

**Comment by codefoster** [comment]
I don't have any links to these videos. Sorry, @VarunSaiTeja.
